import discord

user_not_in_vc = discord.Embed(title="**You cannot do that!**", description="Join a voice channel before running this command!", color=0x9999FF)
bot_not_in_vc = discord.Embed(title="**You cannot do that!**", description="I must be in a voice channel for this to work!", color=0x9999FF)
no_track_found = discord.Embed(title="**No tracks were found!**", description="Try again with a different search query!", color=0x9999FF)
user_bot_channel = discord.Embed(title="**You cannot do that!**", description="We must be in the same voice channel for this to work!", color=0x9999FF)
enter_song = discord.Embed(title="**Incorrect command usage!**", description="You need to enter a song for me to play! !play <song> or !queue <song>.", color=0x9999FF)
empty_queue = discord.Embed(title="**Empty queue!**", description="The queue is empty. Add some songs to the queue using !queue.", color=0x9999FF)
end_of_queue = discord.Embed(title="**Queue has ended!**", description="We've reached the end of the queue! Add more songs using !queue.", color=0x9999FF)
skipped_song = discord.Embed(title="**Skipped song!**", description="Successfully skipped to the next track.", color=0x9999FF)
skip_looped = discord.Embed(title="**Skipped song!**", description="The track is looped, so we're playing the same song again.", color=0x9999FF)
mythic_error = discord.Embed(title="**Mythic Error Pull**", description="Wow! You've discovered a rare error. Congrats. This may or may not get fixed in the future.", color=0xFCBC26)
nothing_to_skip = discord.Embed(title="**Nothing to skip!**", description="There's nothing to skip! We're at the end of the track already.", color=0x9999FF)
bot_is_paused = discord.Embed(title="**Song is paused!**", description="The song is already paused. You can't pause it again. Use !unpause to unpause it.", color=0x9999FF)
no_song_playing = discord.Embed(title="**There is nothing to pause or unpause!**", description="There is no song being played or paused. Play a song using !queue or !play", color=0x9999FF)
pause_success = discord.Embed(title="**Song paused!**", description="The song has been paused. To unpause, use !unpause", color=0x9999FF)
unpause_success = discord.Embed(title="**Song unpaused!**", description="The song has been unpaused. To pause, use !pause", color=0x9999FF)
bot_is_unpaused = discord.Embed(title="**Song is unpaused!**", description="The song is already unpaused. You can't unpause it again. Use !pause to pause it.", color=0x9999FF)
enter_jump_position = discord.Embed(title="**Incorrect command usage!**", description="You need to enter a position for me to play at! !jump <position>.", color=0x9999FF)
invalid_position = discord.Embed(title="**Invalid position!**", description="You need to enter a valid position in the queue. Use !queue to check the queue.", color=0x9999FF)
queue_cleared = discord.Embed(title="**Queue cleared!**", description="Queue cleared successfully. To disconnect the bot, use !disconnect", color=0x9999FF)
disconnected_success = discord.Embed(title="**Disconnected!**", description="I've left the channel! Goodbye!", color=0x9999FF)
no_prev_song = discord.Embed(title="**No previous song!**", description="No songs were played before this! Use !play or !queue to play a song.", color=0x9999FF)
not_a_command = discord.Embed(title="**Not a command!**", description="That is not a command! To see full list of commands, use !help.", color=0x9999FF)

command_list = discord.Embed(title="**Command List**", description="Here are all the commands I have and their use cases:", color=0x9999FF)
command_list.add_field(name="**1. !play <song>**", value="Stops the current playing song if any, then plays the song given by the user.", inline=False)
command_list.add_field(name="**2. !queue <song>**", value="Adds the song given by the user to the queue. If no song is provided, it will show the queue instead.", inline=False)
command_list.add_field(name="**3. !unqueue**", value="Removes the song at the given position from the queue.", inline=False)
command_list.add_field(name="**4. !skip**", value="Skips the current song and plays the next song in queue if any.", inline=False)
command_list.add_field(name="**5. !pause**", value="Pauses the current playing song.", inline=False)
command_list.add_field(name="**6. !unpause**", value="Unpauses the current playing song.", inline=False)
command_list.add_field(name="**7. !jump <position>**", value="Stops the current playing song if any, then plays the song at the position in queue given by the user. This will remove any song before this position from the queue.", inline=False)
command_list.add_field(name="**8. !clear**", value="Stops the current playing song if any, then clears the queue if any. Using this command will also clear the song history for !back.", inline=False)
command_list.add_field(name="**9. !disconnect**", value="Stops the current playing song if any, then clears the queue if any. Then leaves the voice channel.", inline=False)
command_list.add_field(name="**10. !back**", value="Stops the current playing song if any, then plays the last played song.", inline=False)
command_list.add_field(name="**11. !loop**", value="Loops or unloop the track. There is no option to loop the queue current.", inline=False)

loop_track = discord.Embed(title="**Looping track!**", description="Now looping track. To unloop, do !unloop again.", color=0x9999FF)
already_looped = discord.Embed(title="**Already looped!**", description="The track is already looped. Use !unloop to unloop.", color=0x9999FF)
cannot_jump_loop = discord.Embed(title="**Track is looped!**", description="The track is looped, therefore you cannot jump. Unloop the track first.", color=0x9999FF)

nothing_to_unloop = discord.Embed(title="**Track not looped!**", description="Nothing is looped. To loop, use !loop", color=0x9999FF)
unloop_successful = discord.Embed(title="**Track unlooped!**", description="The track has been unlooped.", color=0x9999FF)

enter_unqueue_position = discord.Embed(title="**Incorrect command usage!**", description="You need to enter a position for me to unqueue at! !queue <position>.", color=0x9999FF)

bot_inactive = discord.Embed(title="**Inactivity**", description="I have been inactive for more than 15 minutes. Goodbye!", color=0x9999FF)

shuffled = discord.Embed(title="**Queue shuffled!**", description="The queue has been shuffled!", color=0x9999FF)